name: Build and deploy RDP server with Getscreen

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Getscreen registration file
        uses: actions/download-artifact@v3
        with:
          name: getscreen-registration-file
          path: /tmp/getscreen-registration-file.json

      - name: Build Windows 10 image
        uses: azure/virtual-machines/win10-build@v1
        with:
          vm-name: rdp-server
          vm-size: Standard_B1s
          license-type: PAYG
          customization-script: |
            # Install Getscreen
            curl https://api.getscreen.me/download/getscreen-agent-windows-amd64.msi > getscreen-agent-windows-amd64.msi
            msiexec /i getscreen-agent-windows-amd64.msi /quiet /norestart
            
            # Install RDP Wrapper
            curl https://github.com/stascorp/rdpwrap/releases/download/v1.6.3/rdpwrap-v1.6.3-win32-amd64.zip > rdpwrap-v1.6.3-win32-amd64.zip
            unzip rdpwrap-v1.6.3-win32-amd64.zip
            
            # Configure RDP Wrapper
            cat /tmp/getscreen-registration-file.json > rdpwrap.ini
            echo "[server]" >> rdpwrap.ini
            echo "port = 3389" >> rdpwrap.ini
            echo "username = hellobb" >> rdpwrap.ini
            echo "password = ROOT1232008" >> rdpwrap.ini
            
            # Start RDP Wrapper
            cd rdpwrap-v1.6.3-win32-amd64
            rdpwinst -u -k
            
            # Start ngrok tunnel
            ngrok tcp 3389
            
      - name: Upload RDP connection information
        uses: actions/upload-artifact@v3
        with:
          name: rdp-connection-info
          path: |
            - ngrok.log
            - rdpwrap.ini
